@startuml

class Unidade {
  - id : long
  - nomeFantasia : String
  + transferirVeiculo(veiculo: Veiculo, destino: Unidade) : void
}

class Veiculo
note top of Veiculo: Definido em DiagramaDeClassesVeiculos.puml

class Manutencao {
  - id : long
  - tipo : String
  - descricao : float
  - dataAgendamento : LocalDateTime
}

class Contrato {
  - id : long
}

class Cliente
note top of Cliente: Definido em DiagramaDeClassesCliente.puml

Unidade "1" -- "0..*" Veiculo : gerencia >
Veiculo "1" -- "0..*" Manutencao : submetido a >
Veiculo "1" --* "1" Contrato
Cliente "1" --* "1" Contrato

@enduml
