@startuml
skinparam classAttributeIconSize 0

class Cliente {
  - documentoIdentidade : String
  - documentoHabilitacao : String
  - telefone : String
}

class Funcionario {
  - matricula : String
  - cargo : Cargo
  - username : String
  - password : String
}

enum Cargo {
  GERENTE
  ATENDENTE
}

class Unidade {
  - nomeUnidade : String
  - endereco : Endereco
}

class Veiculo {
  - placa : String
  - marca : String
  - modelo : String
  - ano : Integer
  - status : StatusVeiculo
}

class Contrato {
  - dataInicio : LocalDateTime
  - dataFimPrevista : LocalDateTime
  - dataFimReal : LocalDateTime
  - kmInicial : Double
  - kmFinal : Double
  - valorTotal : Double
}

class Manutencao {
  - descricao : String
  - custo : Double
  - tipo : TipoManutencao
}

Funcionario "0..*" -- "1" Unidade : trabalha em >
Unidade "1" -- "0..*" Veiculo : gerencia >
Cliente "1" -- "0..*" Contrato : realiza >
Veiculo "1" -- "0..*" Contrato : possui histórico em >
Veiculo "1" -- "0..*" Manutencao : submetido a >
Funcionario --> Cargo
Veiculo --> StatusVeiculo

@enduml
