@startuml

class Veiculo {
  - id: long
  - placa : String
  - marca : String
  - modelo : String
  - ano : Year
  - chassi : String
  - status : StatusVeiculo
  - kmAtual : float
  - documentosAnexados : List<File>
  - criadoEm : LocalDateTime
  - atualizadoEm : LocalDateTime
  + Veiculo()
  + atualizarStatus(novoStatus: StatusVeiculo) : void
  + atualizarKm(kmAtual: Float) : void
}

enum StatusVeiculo {
  DISPONIVEL
  INDISPONIVEL
  EM_USO
  MANUTENCAO
}
@enduml
