@startuml

class Cliente {
  - id: long
  - nome : String
  - documentoIdentidade : String
  - codHabilitacao : String
  - telefone : String
  - criadoEm : LocalDateTime
  - atualizadoEm : LocalDateTime
  + Cliente()
  + validarDocumento(): boolean
  + atualizarDados(UpdateClienteDTO clienteAtualizado) : void
}

class UpdateClienteDTO {
  - nome : String
  - documentoIdentidade : String
  - codHabilitacao : String
  - telefone : String
}
@enduml